# Generated by Django 2.2.1 on 2019-05-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
