# Generated by Django 2.2.1 on 2019-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='order',
            field=models.IntegerField(blank=True),
        ),
    ]
