# Generated by Django 2.2.1 on 2019-05-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20190523_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='order',
        ),
    ]
