# Generated by Django 2.2.1 on 2019-06-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_exhibition_is_horizontal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='is_horizontal',
            new_name='is_vertical',
        ),
    ]
