# Generated by Django 2.2.1 on 2020-10-29 17:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_left', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('content_right', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
