# Generated by Django 2.2.1 on 2019-06-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tearsheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tearsheet',
            name='is_vertical',
            field=models.BooleanField(default=True),
        ),
    ]
