# Generated by Django 2.2.1 on 2019-05-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
